//在控制台输出当前node.js进程运行所在的操作系统平台
console.log(process.platform);
//在控制台输出当前node.js进程的PID
console.log(process.pid);
//文件路径是指该文件存储在哪里
console.log(process.argv[1]);
//文件目录是指该文件存储在哪个磁盘下，该磁盘的位置
console.log(process.argv[0]);
//在控制台输出谷歌V8的内存使用情况
console.log(process.memoryUsage());
